language: node_js

node_js:
  - "13"

# Use container-based Travis infrastructure.
sudo: required

addons:
  hosts:
    - your-keyvalue-store.local

branches:
  only:
    - master

install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install -y --force-yes nginx-extras

before_script:
  - npm install

script:
  - sudo test/install-nginx.sh
  - node server.js &
  - npm test