language: node_js

node_js:
  - "13"

# Use container-based Travis infrastructure.
sudo: required

addons:
  hosts:
    - your-keyvalue-store.local

branches:
  only:
    - master

install:
  - sudo add-apt-repository -y ppa:nginx/stable
  - sudo apt-get update
  - sudo apt-get install -y --force-yes nginx-extras
  - sudo rm /etc/nginx/sites-available/default
  - sudo cp $TRAVIS_BUILD_DIR/server.conf /etc/nginx/sites-available/keyval-server.conf
  - sudo sed 's/\/path\/to\/your\/keyvalue-store\/data\//\/tmp\/keyval\//g' /etc/nginx/sites-available/keyval-server.conf > /etc/nginx/sites-available/keyval-server.conf
  - sudo ln -s /etc/nginx/sites-available/keyval-server.conf /etc/nginx/sites-enabled/keyval-server.conf
  - sudo nginx -c /etc/nginx/nginx.conf
  - sudo service nginx reload

before_script:
  - npm install

script:
  - node server.js &
  - npm test